name: Test workflow

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Echo the name
        run: |
          export NAME=Mathias
          echo the $NAME